/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */

buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlinVersion}")
  }
}

allprojects {
  group = AppConfig.group
}

subprojects {
  repositories {
    google()
    mavenCentral()
  }
}

tasks {
  wrapper {
    gradleVersion = "7.1.1"
    distributionType = Wrapper.DistributionType.BIN
  }
}
