/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1.1/userguide/multi_project_builds.html
 */

rootProject.name = "lsbasi"

include(
  "part1",
  "part2"
)

for (project in rootProject.children) {
  project.apply {
    projectDir = file("subprojects/$name")
    buildFileName = "$name.gradle.kts"
    require(projectDir.isDirectory) { "Project '${project.path} must have a $projectDir directory" }
    require(buildFile.isFile) { "Project '${project.path} must have a $buildFile build script" }
  }
}